#!/usr/bin/env python
# encoding: utf-8
from __future__ import print_function
import sys

def build_prog(bld, progname):
    bld.program(
        source = progname + '.cpp',
        target = progname,
        includes = [ '.', '..', '../3rdparty', '../algorithms', '../metrics' ],
        use = ['gaia2'] + bld.env['USELIB'],
        install_path = 0 # do not install
        )
    

def build(bld):
    list_progs = [ 'nnsearch', 'unittest',
                   'testmemleak', 'testoptimization' ]

    for prog in list_progs:
        build_prog(bld, prog)

    if bld.env['WITH_STLFACADE']:
        build_prog(bld, 'facadetest')


def set_options(opt):
    pass

def configure(conf):
    pass
