#!/usr/bin/env python
# encoding: utf-8

# <copyright entity="UPF">
# UPF. All Right Reserved, http://www.upf.edu/
#
# This source is subject to the Contributor License Agreement of the Essentia project.
# Please see the CLA.txt file available at http://essentia.upf.edu/contribute/
# for more
# information.
# 
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
# KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
#
# </copyright>

from __future__ import print_function
import sys

def build_prog(bld, progname):
    bld.program(
        source = progname + '.cpp',
        target = progname,
        includes = [ '.', '..', '../3rdparty', '../algorithms', '../metrics' ],
        use = ['gaia2'] + bld.env['USELIB'],
        install_path = 0 # do not install
        )
    

def build(bld):
    list_progs = [ 'nnsearch', 'unittest',
                   'testmemleak', 'testoptimization' ]

    for prog in list_progs:
        build_prog(bld, prog)

    if bld.env['WITH_STLFACADE']:
        build_prog(bld, 'facadetest')


def set_options(opt):
    pass

def configure(conf):
    pass
