#!/usr/bin/env python
# encoding: utf-8


def build_with_gaia(bld, prog):
    prog.includes = [ '.', '..', '../3rdparty', '../algorithms', '../metrics' ]
    prog.uselib_local = 'gaia2'
    prog.uselib = bld.env['USELIB']
    prog.install_path = 0 # do not install


def build_prog(bld, progname):
    prog = bld.new_task_gen('cxx', 'program')
    prog.target = progname
    prog.source = progname + '.cpp'
    build_with_gaia(bld, prog)

def build(bld):
    list_progs = [ 'nnsearch', 'unittest',
                   'testmemleak', 'testoptimization' ]

    for prog in list_progs:
        build_prog(bld, prog)

    if bld.env_of_name('default')['WITH_STLFACADE']:
        build_prog(bld, 'facadetest')


def set_options(opt):
    pass

def configure(conf):
    pass
