#define AND                             1
#define OR                              2
#define EQ                              3
#define NEQ                             4
#define GT                              5
#define GTE                             6
#define LT                              7
#define LTE                             8
#define WHERE                           9
#define COMMA                          10
#define NOT                            11
#define PAREN_OPEN                     12
#define PAREN_CLOSE                    13
#define BETWEEN                        14
#define BOOL_CONSTANT                  15
#define IN                             16
#define STRING                         17
#define LABEL_VARIABLE                 18
#define POINT_ID                       19
#define VALUE_CONSTANT                 20
#define VALUE_VARIABLE                 21
